import Form from '../components/AgeForm'
import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Age Calculator App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.png' />
			</Head>
			<main>
				<section className='hero is-fullheight'>
					<div className='hero-body'>
						<div className='container'>
							<div className='calculator-container'>
								<Form />
							</div>
						</div>
					</div>
				</section>
			</main>
		</>
	)
}
